export const sablierMerkleVCAAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "campaignParams",
        type: "tuple",
        internalType: "struct MerkleVCA.ConstructorParams",
        components: [
          { name: "aggregateAmount", type: "uint128", internalType: "uint128" },
          { name: "campaignName", type: "string", internalType: "string" },
          { name: "campaignStartTime", type: "uint40", internalType: "uint40" },
          { name: "claimType", type: "uint8", internalType: "enum ClaimType" },
          { name: "enableRedistribution", type: "bool", internalType: "bool" },
          { name: "expiration", type: "uint40", internalType: "uint40" },
          { name: "initialAdmin", type: "address", internalType: "address" },
          { name: "ipfsCID", type: "string", internalType: "string" },
          { name: "merkleRoot", type: "bytes32", internalType: "bytes32" },
          { name: "token", type: "address", internalType: "contract IERC20" },
          { name: "unlockPercentage", type: "uint256", internalType: "UD60x18" },
          { name: "vestingEndTime", type: "uint40", internalType: "uint40" },
          { name: "vestingStartTime", type: "uint40", internalType: "uint40" },
        ],
      },
      { name: "campaignCreator", type: "address", internalType: "address" },
      { name: "comptroller", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "AGGREGATE_AMOUNT",
    inputs: [],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CAMPAIGN_START_TIME",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CLAIM_TYPE",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "enum ClaimType" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "COMPTROLLER",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "EXPIRATION",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "IS_SABLIER_MERKLE",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MERKLE_ROOT",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TOKEN",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "UNLOCK_PERCENTAGE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "UD60x18" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "VESTING_END_TIME",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "VESTING_START_TIME",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "attestor",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateClaimAmount",
    inputs: [
      { name: "fullAmount", type: "uint128", internalType: "uint128" },
      { name: "claimTime", type: "uint40", internalType: "uint40" },
    ],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateForgoneAmount",
    inputs: [
      { name: "fullAmount", type: "uint128", internalType: "uint128" },
      { name: "claimTime", type: "uint40", internalType: "uint40" },
    ],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateMinFeeWei",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateRedistributionRewards",
    inputs: [{ name: "fullAmount", type: "uint128", internalType: "uint128" }],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "campaignName",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimTo",
    inputs: [
      { name: "index", type: "uint256", internalType: "uint256" },
      { name: "to", type: "address", internalType: "address" },
      { name: "fullAmount", type: "uint128", internalType: "uint128" },
      { name: "merkleProof", type: "bytes32[]", internalType: "bytes32[]" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimViaAttestation",
    inputs: [
      { name: "index", type: "uint256", internalType: "uint256" },
      { name: "to", type: "address", internalType: "address" },
      { name: "fullAmount", type: "uint128", internalType: "uint128" },
      { name: "expireAt", type: "uint40", internalType: "uint40" },
      { name: "merkleProof", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "attestation", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimViaSig",
    inputs: [
      { name: "index", type: "uint256", internalType: "uint256" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "fullAmount", type: "uint128", internalType: "uint128" },
      { name: "validFrom", type: "uint40", internalType: "uint40" },
      { name: "merkleProof", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "clawback",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "domainSeparator",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "enableRedistribution",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "firstClaimTime",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClaimed",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasExpired",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ipfsCID",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isRedistributionEnabled",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lowerMinFeeUSD",
    inputs: [{ name: "newMinFeeUSD", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "minFeeUSD",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAttestor",
    inputs: [{ name: "newAttestor", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sponsor",
    inputs: [
      { name: "token", type: "address", internalType: "contract IERC20" },
      { name: "amount", type: "uint128", internalType: "uint128" },
      { name: "biller", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalForgoneAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalRedistributionAmountPaid",
    inputs: [],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferAdmin",
    inputs: [{ name: "newAdmin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ClaimVCA",
    inputs: [
      { name: "index", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "claimAmount", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "forgoneAmount", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "to", type: "address", indexed: false, internalType: "address" },
      { name: "viaSig", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Clawback",
    inputs: [
      { name: "admin", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint128", indexed: false, internalType: "uint128" },
    ],
    anonymous: false,
  },
  { type: "event", name: "EnableRedistribution", inputs: [], anonymous: false },
  {
    type: "event",
    name: "LowerMinFeeUSD",
    inputs: [
      { name: "comptroller", type: "address", indexed: true, internalType: "address" },
      { name: "newMinFeeUSD", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "previousMinFeeUSD", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RedistributeReward",
    inputs: [
      { name: "index", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "to", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetAttestor",
    inputs: [
      { name: "caller", type: "address", indexed: true, internalType: "address" },
      { name: "previousAttestor", type: "address", indexed: true, internalType: "address" },
      { name: "newAttestor", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Sponsor",
    inputs: [
      { name: "caller", type: "address", indexed: true, internalType: "address" },
      { name: "token", type: "address", indexed: true, internalType: "contract IERC20" },
      { name: "amount", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "biller", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TransferAdmin",
    inputs: [
      { name: "oldAdmin", type: "address", indexed: true, internalType: "address" },
      { name: "newAdmin", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "CallerNotAdmin",
    inputs: [
      { name: "admin", type: "address", internalType: "address" },
      { name: "caller", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "PRBMath_MulDiv18_Overflow",
    inputs: [
      { name: "x", type: "uint256", internalType: "uint256" },
      { name: "y", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "PRBMath_UD60x18_IntoUint128_Overflow",
    inputs: [{ name: "x", type: "uint256", internalType: "UD60x18" }],
  },
  {
    type: "error",
    name: "SablierMerkleBase_CallerNotComptroller",
    inputs: [
      { name: "comptroller", type: "address", internalType: "address" },
      { name: "caller", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "SablierMerkleBase_CampaignExpired",
    inputs: [
      { name: "blockTimestamp", type: "uint256", internalType: "uint256" },
      { name: "expiration", type: "uint40", internalType: "uint40" },
    ],
  },
  {
    type: "error",
    name: "SablierMerkleBase_CampaignNotStarted",
    inputs: [
      { name: "blockTimestamp", type: "uint256", internalType: "uint256" },
      { name: "campaignStartTime", type: "uint40", internalType: "uint40" },
    ],
  },
  {
    type: "error",
    name: "SablierMerkleBase_ClawbackNotAllowed",
    inputs: [
      { name: "blockTimestamp", type: "uint256", internalType: "uint256" },
      { name: "expiration", type: "uint40", internalType: "uint40" },
      { name: "firstClaimTime", type: "uint40", internalType: "uint40" },
    ],
  },
  {
    type: "error",
    name: "SablierMerkleBase_FeeTransferFailed",
    inputs: [
      { name: "feeRecipient", type: "address", internalType: "address" },
      { name: "feeAmount", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "SablierMerkleBase_IndexClaimed",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "SablierMerkleBase_InsufficientFeePayment",
    inputs: [
      { name: "feePaid", type: "uint256", internalType: "uint256" },
      { name: "minFeeWei", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "SablierMerkleBase_InvalidProof", inputs: [] },
  {
    type: "error",
    name: "SablierMerkleBase_NewMinFeeUSDNotLower",
    inputs: [
      { name: "currentMinFeeUSD", type: "uint256", internalType: "uint256" },
      { name: "newMinFeeUSD", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "SablierMerkleBase_SponsorAmountZero", inputs: [] },
  { type: "error", name: "SablierMerkleBase_ToZeroAddress", inputs: [] },
  {
    type: "error",
    name: "SablierMerkleBase_UnsupportedClaimType",
    inputs: [
      { name: "claimTypeRequired", type: "uint8", internalType: "enum ClaimType" },
      { name: "claimTypeSupported", type: "uint8", internalType: "enum ClaimType" },
    ],
  },
  {
    type: "error",
    name: "SablierMerkleSignature_AttestationExpired",
    inputs: [
      { name: "expireAt", type: "uint256", internalType: "uint256" },
      { name: "blockTimestamp", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "SablierMerkleSignature_AttestorNotSet", inputs: [] },
  {
    type: "error",
    name: "SablierMerkleSignature_CallerNotAuthorized",
    inputs: [
      { name: "caller", type: "address", internalType: "address" },
      { name: "campaignAdmin", type: "address", internalType: "address" },
      { name: "comptroller", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "SablierMerkleSignature_InvalidSignature", inputs: [] },
  {
    type: "error",
    name: "SablierMerkleSignature_SignatureNotYetValid",
    inputs: [
      { name: "validFrom", type: "uint40", internalType: "uint40" },
      { name: "blockTimestamp", type: "uint40", internalType: "uint40" },
    ],
  },
  {
    type: "error",
    name: "SablierMerkleVCA_ClaimAmountZero",
    inputs: [{ name: "recipient", type: "address", internalType: "address" }],
  },
  { type: "error", name: "SablierMerkleVCA_RedistributionAlreadyEnabled", inputs: [] },
  { type: "error", name: "SablierMerkleVCA_RedistributionNotEnabled", inputs: [] },
  {
    type: "error",
    name: "SablierMerkleVCA_VestingEndTimeNotInFuture",
    inputs: [
      { name: "vestingEndTime", type: "uint256", internalType: "uint256" },
      { name: "blockTimestamp", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "SablierMerkleVCA_VestingNotStarted",
    inputs: [
      { name: "claimTime", type: "uint40", internalType: "uint40" },
      { name: "vestingStartTime", type: "uint40", internalType: "uint40" },
    ],
  },
  {
    type: "error",
    name: "SafeCastOverflowedUintDowncast",
    inputs: [
      { name: "bits", type: "uint8", internalType: "uint8" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
] as const;
