export const sablierFactoryMerkleInstantAbi = [
  {
    inputs: [{ internalType: "address", name: "initialComptroller", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      { internalType: "address", name: "comptroller", type: "address" },
      { internalType: "address", name: "caller", type: "address" },
    ],
    name: "Comptrollerable_CallerNotComptroller",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "previousComptroller", type: "address" },
      { internalType: "address", name: "newComptroller", type: "address" },
      { internalType: "bytes4", name: "minimalInterfaceId", type: "bytes4" },
    ],
    name: "Comptrollerable_UnsupportedInterfaceId",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "nativeToken", type: "address" }],
    name: "SablierFactoryMerkleBase_ForbidNativeToken",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "nativeToken", type: "address" }],
    name: "SablierFactoryMerkleBase_NativeTokenAlreadySet",
    type: "error",
  },
  { inputs: [], name: "SablierFactoryMerkleBase_NativeTokenZeroAddress", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract ISablierMerkleInstant",
        name: "merkleInstant",
        type: "address",
      },
      {
        components: [
          { internalType: "string", name: "campaignName", type: "string" },
          { internalType: "uint40", name: "campaignStartTime", type: "uint40" },
          { internalType: "uint40", name: "expiration", type: "uint40" },
          { internalType: "address", name: "initialAdmin", type: "address" },
          { internalType: "string", name: "ipfsCID", type: "string" },
          { internalType: "bytes32", name: "merkleRoot", type: "bytes32" },
          { internalType: "contract IERC20", name: "token", type: "address" },
        ],
        indexed: false,
        internalType: "struct MerkleInstant.ConstructorParams",
        name: "params",
        type: "tuple",
      },
      { indexed: false, internalType: "uint256", name: "aggregateAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "recipientCount", type: "uint256" },
      { indexed: false, internalType: "address", name: "comptroller", type: "address" },
      { indexed: false, internalType: "uint256", name: "minFeeUSD", type: "uint256" },
    ],
    name: "CreateMerkleInstant",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract ISablierComptroller",
        name: "oldComptroller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "contract ISablierComptroller",
        name: "newComptroller",
        type: "address",
      },
    ],
    name: "SetComptroller",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "comptroller", type: "address" },
      { indexed: false, internalType: "address", name: "nativeToken", type: "address" },
    ],
    name: "SetNativeToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract ISablierComptroller",
        name: "comptroller",
        type: "address",
      },
      { indexed: false, internalType: "uint256", name: "feeAmount", type: "uint256" },
    ],
    name: "TransferFeesToComptroller",
    type: "event",
  },
  {
    inputs: [],
    name: "comptroller",
    outputs: [{ internalType: "contract ISablierComptroller", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "campaignCreator", type: "address" },
      {
        components: [
          { internalType: "string", name: "campaignName", type: "string" },
          { internalType: "uint40", name: "campaignStartTime", type: "uint40" },
          { internalType: "uint40", name: "expiration", type: "uint40" },
          { internalType: "address", name: "initialAdmin", type: "address" },
          { internalType: "string", name: "ipfsCID", type: "string" },
          { internalType: "bytes32", name: "merkleRoot", type: "bytes32" },
          { internalType: "contract IERC20", name: "token", type: "address" },
        ],
        internalType: "struct MerkleInstant.ConstructorParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "computeMerkleInstant",
    outputs: [{ internalType: "address", name: "merkleInstant", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "campaignName", type: "string" },
          { internalType: "uint40", name: "campaignStartTime", type: "uint40" },
          { internalType: "uint40", name: "expiration", type: "uint40" },
          { internalType: "address", name: "initialAdmin", type: "address" },
          { internalType: "string", name: "ipfsCID", type: "string" },
          { internalType: "bytes32", name: "merkleRoot", type: "bytes32" },
          { internalType: "contract IERC20", name: "token", type: "address" },
        ],
        internalType: "struct MerkleInstant.ConstructorParams",
        name: "params",
        type: "tuple",
      },
      { internalType: "uint256", name: "aggregateAmount", type: "uint256" },
      { internalType: "uint256", name: "recipientCount", type: "uint256" },
    ],
    name: "createMerkleInstant",
    outputs: [
      { internalType: "contract ISablierMerkleInstant", name: "merkleInstant", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nativeToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "contract ISablierComptroller", name: "newComptroller", type: "address" },
    ],
    name: "setComptroller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newNativeToken", type: "address" }],
    name: "setNativeToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "transferFeesToComptroller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
