// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export const errorCodes = {
  StreamDepleted: 6000,
  StreamCanceled: 6001,
  StreamIsNotCancelable: 6002,
  StreamSettled: 6003,
  CantCollectZeroFees: 6004,
  CliffTimeNotLessThanEndTime: 6005,
  CliffTimeZeroUnlockAmountNotZero: 6006,
  DepositAmountZero: 6007,
  StartTimeNotLessThanCliffTime: 6008,
  StartTimeNotLessThanEndTime: 6009,
  StartTimeZero: 6010,
  UnlockAmountsSumTooHigh: 6011,
  StreamAlreadyNonCancelable: 6012,
  Overdraw: 6013,
  WithdrawAmountZero: 6014,
} as const;

export type ErrorNames = keyof typeof errorCodes;
