name: "Cron: Tests"

on:
  schedule:
    # Runs at 02:00 UTC every Sunday
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Set up devkit"
        uses: "sablier-labs/devkit/actions/setup@main"
        with:
          package-manager: "bun"

      - name: "Check the code"
        run: "just full-check"

      - name: "Run the tests"
        id: tests
        continue-on-error: true
        env:
          VITE_CRON_TESTS: true
          VITE_ETHERSCAN_API_KEY: ${{ secrets.VITE_ETHERSCAN_API_KEY }}
        run: "just test"

      - name: "Generate test summary"
        if: always()
        run: "bun run ./scripts/summarize-test-failures.ts >> $GITHUB_STEP_SUMMARY"
