export const sablierEscrowAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "initialComptroller", type: "address", internalType: "address" },
      { name: "initialTradeFee", type: "uint256", internalType: "UD60x18" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "MAX_TRADE_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "UD60x18" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelOrder",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "comptroller",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract ISablierComptroller" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createOrder",
    inputs: [
      { name: "sellToken", type: "address", internalType: "contract IERC20" },
      { name: "sellAmount", type: "uint128", internalType: "uint128" },
      { name: "buyToken", type: "address", internalType: "contract IERC20" },
      { name: "minBuyAmount", type: "uint128", internalType: "uint128" },
      { name: "buyer", type: "address", internalType: "address" },
      { name: "expiryTime", type: "uint40", internalType: "uint40" },
    ],
    outputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fillOrder",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "buyAmount", type: "uint128", internalType: "uint128" },
    ],
    outputs: [
      { name: "amountToTransferToSeller", type: "uint128", internalType: "uint128" },
      { name: "amountToTransferToBuyer", type: "uint128", internalType: "uint128" },
      { name: "feeDeductedFromBuyerAmount", type: "uint128", internalType: "uint128" },
      { name: "feeDeductedFromSellerAmount", type: "uint128", internalType: "uint128" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getBuyToken",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "buyToken", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBuyer",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "buyer", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getExpiryTime",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "expiryTime", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMinBuyAmount",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "minBuyAmount", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSellAmount",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "sellAmount", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSellToken",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "sellToken", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSeller",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "seller", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nativeToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextOrderId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setComptroller",
    inputs: [
      { name: "newComptroller", type: "address", internalType: "contract ISablierComptroller" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setNativeToken",
    inputs: [{ name: "newNativeToken", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTradeFee",
    inputs: [{ name: "newTradeFee", type: "uint256", internalType: "UD60x18" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "statusOf",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "status", type: "uint8", internalType: "enum Escrow.Status" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tradeFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "UD60x18" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferFeesToComptroller",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "wasCanceled",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "result", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "wasFilled",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "result", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CancelOrder",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "sellAmount", type: "uint128", indexed: false, internalType: "uint128" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreateOrder",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "sellToken", type: "address", indexed: false, internalType: "contract IERC20" },
      { name: "buyToken", type: "address", indexed: false, internalType: "contract IERC20" },
      { name: "sellAmount", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "minBuyAmount", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "expiryTime", type: "uint40", indexed: false, internalType: "uint40" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FillOrder",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "sellAmount", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "buyAmount", type: "uint128", indexed: false, internalType: "uint128" },
      {
        name: "feeDeductedFromBuyerAmount",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "feeDeductedFromSellerAmount",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetComptroller",
    inputs: [
      {
        name: "oldComptroller",
        type: "address",
        indexed: false,
        internalType: "contract ISablierComptroller",
      },
      {
        name: "newComptroller",
        type: "address",
        indexed: false,
        internalType: "contract ISablierComptroller",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetNativeToken",
    inputs: [
      { name: "comptroller", type: "address", indexed: true, internalType: "address" },
      { name: "nativeToken", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetTradeFee",
    inputs: [
      { name: "caller", type: "address", indexed: true, internalType: "address" },
      { name: "previousTradeFee", type: "uint256", indexed: false, internalType: "UD60x18" },
      { name: "newTradeFee", type: "uint256", indexed: false, internalType: "UD60x18" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TransferFeesToComptroller",
    inputs: [
      { name: "comptroller", type: "address", indexed: true, internalType: "address" },
      { name: "feeAmount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "Comptrollerable_CallerNotComptroller",
    inputs: [
      { name: "comptroller", type: "address", internalType: "address" },
      { name: "caller", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "Comptrollerable_UnsupportedInterfaceId",
    inputs: [
      { name: "previousComptroller", type: "address", internalType: "address" },
      { name: "newComptroller", type: "address", internalType: "address" },
      { name: "minimalInterfaceId", type: "bytes4", internalType: "bytes4" },
    ],
  },
  {
    type: "error",
    name: "PRBMath_MulDiv18_Overflow",
    inputs: [
      { name: "x", type: "uint256", internalType: "uint256" },
      { name: "y", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "PRBMath_UD60x18_IntoUint128_Overflow",
    inputs: [{ name: "x", type: "uint256", internalType: "UD60x18" }],
  },
  {
    type: "error",
    name: "SablierEscrowState_NewTradeFeeTooHigh",
    inputs: [
      { name: "newTradeFee", type: "uint256", internalType: "UD60x18" },
      { name: "maxTradeFee", type: "uint256", internalType: "UD60x18" },
    ],
  },
  {
    type: "error",
    name: "SablierEscrowState_Null",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "SablierEscrow_BuyTokenZero", inputs: [] },
  {
    type: "error",
    name: "SablierEscrow_CallerNotAuthorized",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "caller", type: "address", internalType: "address" },
      { name: "expectedCaller", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "SablierEscrow_ExpiryTimeInPast",
    inputs: [
      { name: "expiryTime", type: "uint40", internalType: "uint40" },
      { name: "currentTime", type: "uint40", internalType: "uint40" },
    ],
  },
  {
    type: "error",
    name: "SablierEscrow_ForbidNativeToken",
    inputs: [{ name: "nativeToken", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "SablierEscrow_InsufficientBuyAmount",
    inputs: [
      { name: "buyAmount", type: "uint128", internalType: "uint128" },
      { name: "minBuyAmount", type: "uint128", internalType: "uint128" },
    ],
  },
  { type: "error", name: "SablierEscrow_MinBuyAmountZero", inputs: [] },
  {
    type: "error",
    name: "SablierEscrow_NativeTokenAlreadySet",
    inputs: [{ name: "nativeToken", type: "address", internalType: "address" }],
  },
  { type: "error", name: "SablierEscrow_NativeTokenZeroAddress", inputs: [] },
  {
    type: "error",
    name: "SablierEscrow_OrderCancelled",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "SablierEscrow_OrderFilled",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "SablierEscrow_OrderNotOpen",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum Escrow.Status" },
    ],
  },
  {
    type: "error",
    name: "SablierEscrow_SameToken",
    inputs: [{ name: "token", type: "address", internalType: "contract IERC20" }],
  },
  { type: "error", name: "SablierEscrow_SellAmountZero", inputs: [] },
  { type: "error", name: "SablierEscrow_SellTokenZero", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
] as const;
